//! Generate SQL to update images.storage_url from migration mappings
//!
//! This script reads the image_migration_mappings.json file generated by
//! migrate_images_to_gcs.rs and creates SQL UPDATE statements.
//!
//! Usage:
//!   cargo run --bin generate-storage-updates --features ssr
//!
//! Output: update_storage_urls.sql

use std::collections::HashMap;
use std::fs::File;
use std::io::{Read, Write};

fn main() -> Result<(), Box<dyn std::error::Error>> {
    println!("Reading image_migration_mappings.json...");

    let mut file = File::open("image_migration_mappings.json")?;
    let mut contents = String::new();
    file.read_to_string(&mut contents)?;

    let mappings: HashMap<String, String> = serde_json::from_str(&contents)?;

    println!("Found {} mappings", mappings.len());

    let output_path = "update_storage_urls.sql";
    let mut output = File::create(output_path)?;

    writeln!(output, "-- SQL to update images.storage_url from migration mappings")?;
    writeln!(output, "-- Generated from image_migration_mappings.json\n")?;
    writeln!(output, "BEGIN;\n")?;

    for (uuid, storage_url) in &mappings {
        writeln!(
            output,
            "UPDATE images SET storage_url = '{}' WHERE id = '{}';",
            storage_url.replace('\'', "''"),
            uuid
        )?;
    }

    writeln!(output, "\n-- Verify all images have storage_url")?;
    writeln!(output, "SELECT COUNT(*) as missing_count FROM images WHERE storage_url IS NULL;\n")?;

    writeln!(output, "COMMIT;")?;

    println!("SQL written to {}", output_path);
    println!("\nNext steps:");
    println!("  1. Review {}", output_path);
    println!("  2. Run: psql $DATABASE_URL -f {}", output_path);

    Ok(())
}
