//! Migration script to move images from PostgreSQL to GCS
//!
//! This script:
//! 1. Reads all images from the PostgreSQL `images` table
//! 2. Uploads each image to GCS using the file-storage crate
//! 3. Creates a mapping file (UUID → storage URL)
//! 4. Generates SQL to update content references
//!
//! Usage:
//!   cargo run --bin migrate-images --features ssr
//!
//! Environment variables required:
//!   DATABASE_URL - PostgreSQL connection string
//!   FILE_STORAGE_BACKEND - Storage backend (gcs)
//!   GCS_BUCKET_NAME - GCS bucket name
//!   GCS_SERVICE_ACCOUNT_KEY - Path to service account JSON

use std::collections::HashMap;
use std::fs::File;
use std::io::Write;

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    // Load environment
    dotenvy::dotenv().ok();

    // Initialize logging
    tracing_subscriber::fmt()
        .with_env_filter(
            tracing_subscriber::EnvFilter::try_from_default_env()
                .unwrap_or_else(|_| tracing_subscriber::EnvFilter::new("info")),
        )
        .init();

    tracing::info!("Starting image migration to GCS...");

    // Connect to PostgreSQL
    let database_url = std::env::var("DATABASE_URL")
        .expect("DATABASE_URL must be set");

    tracing::info!("Connecting to database...");
    let pool = sqlx::postgres::PgPoolOptions::new()
        .max_connections(5)
        .connect(&database_url)
        .await?;

    tracing::info!("Connected to database");

    // Create file storage client
    let storage_client = file_storage::create_client_from_env()
        .expect("Failed to create storage client - check FILE_STORAGE_BACKEND, GCS_BUCKET_NAME, GCS_SERVICE_ACCOUNT_KEY");

    tracing::info!("Storage client created: {}", storage_client.backend_name());

    // Query all images
    tracing::info!("Fetching images from database...");

    #[derive(Debug, sqlx::FromRow)]
    struct ImageRow {
        id: uuid::Uuid,
        filename: String,
        mime_type: String,
        data: Vec<u8>,
        size_bytes: i64,
        category: Option<String>,
    }

    let images: Vec<ImageRow> = sqlx::query_as(
        "SELECT id, filename, mime_type, data, size_bytes, category FROM images ORDER BY created_at"
    )
    .fetch_all(&pool)
    .await?;

    tracing::info!("Found {} images to migrate", images.len());

    if images.is_empty() {
        tracing::info!("No images to migrate. Exiting.");
        return Ok(());
    }

    // Migrate each image
    let mut mappings: HashMap<String, String> = HashMap::new();
    let mut success_count = 0;
    let mut error_count = 0;

    for (index, image) in images.iter().enumerate() {
        tracing::info!(
            "[{}/{}] Migrating image {} ({}, {} bytes)",
            index + 1,
            images.len(),
            image.id,
            image.filename,
            image.size_bytes
        );

        // Use category or "uncategorized" as resource prefix
        let resource_id = image.category.clone().unwrap_or_else(|| "images".to_string());
        let resource_id = format!("{}/{}", resource_id, image.id);

        match storage_client
            .upload_file(&resource_id, image.data.clone(), &image.filename, &image.mime_type)
            .await
        {
            Ok(storage_url) => {
                let old_url = format!("/api/images/{}", image.id);
                tracing::info!("  ✓ Uploaded: {} → {}", old_url, storage_url);
                mappings.insert(image.id.to_string(), storage_url);
                success_count += 1;
            }
            Err(e) => {
                tracing::error!("  ✗ Failed to upload {}: {}", image.id, e);
                error_count += 1;
            }
        }
    }

    tracing::info!("\nMigration complete:");
    tracing::info!("  Success: {}", success_count);
    tracing::info!("  Errors:  {}", error_count);

    // Write mappings to JSON file
    let mappings_json = serde_json::to_string_pretty(&mappings)?;
    let mappings_path = "image_migration_mappings.json";
    let mut file = File::create(mappings_path)?;
    file.write_all(mappings_json.as_bytes())?;
    tracing::info!("Mappings written to {}", mappings_path);

    // Generate SQL update script for content references
    let sql_path = "update_content_references.sql";
    let mut sql_file = File::create(sql_path)?;

    writeln!(sql_file, "-- SQL script to update content references")?;
    writeln!(sql_file, "-- Generated by migrate_images_to_gcs.rs")?;
    writeln!(sql_file, "-- Review before executing!\n")?;

    writeln!(sql_file, "BEGIN;\n")?;

    // Update page_contents table (legacy content)
    writeln!(sql_file, "-- Update page_contents table")?;
    for (uuid, storage_url) in &mappings {
        let old_pattern = format!("/api/images/{}", uuid);
        writeln!(
            sql_file,
            "UPDATE page_contents SET content = REPLACE(content::text, '{}', '{}')::jsonb WHERE content::text LIKE '%{}%';",
            old_pattern, storage_url, old_pattern
        )?;
    }

    writeln!(sql_file, "\n-- Update content_items table (schema-driven content)")?;
    for (uuid, storage_url) in &mappings {
        let old_pattern = format!("/api/images/{}", uuid);
        writeln!(
            sql_file,
            "UPDATE content_items SET data = REPLACE(data::text, '{}', '{}')::jsonb WHERE data::text LIKE '%{}%';",
            old_pattern, storage_url, old_pattern
        )?;
    }

    writeln!(sql_file, "\nCOMMIT;")?;

    tracing::info!("SQL update script written to {}", sql_path);
    tracing::info!("\nNext steps:");
    tracing::info!("  1. Review {} for mapping correctness", mappings_path);
    tracing::info!("  2. Review {} before running", sql_path);
    tracing::info!("  3. Run SQL script: psql $DATABASE_URL -f {}", sql_path);
    tracing::info!("  4. After verification, you can drop the 'data' column from images table");

    Ok(())
}
