{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "uno-app.serviceAccountName" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "uno-app.labels" . | nindent 4 }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
{{- end }}
