{{- if and .Values.cloudflared.enabled .Values.networkPolicy.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: cloudflared-policy
  namespace: {{ .Values.cloudflared.namespace }}
  labels:
    {{- include "cloudflared.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "cloudflared.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Egress
  egress:
    # Allow DNS
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: UDP
          port: 53
    # Allow to uno-app
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Values.global.namespace }}
          podSelector:
            matchLabels:
              app: uno-app
      ports:
        - protocol: TCP
          port: {{ .Values.app.probes.port }}
    # Allow to Cloudflare endpoints
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
            except:
              - 10.0.0.0/8
              - 172.16.0.0/12
              - 192.168.0.0/16
      ports:
        {{- range .Values.networkPolicy.cloudflareEgressPorts }}
        - protocol: TCP
          port: {{ . }}
        {{- end }}
{{- end }}
