{{- if .Values.cloudflared.enabled -}}
# Placeholder secret - populate before deployment
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel
  namespace: {{ .Values.cloudflared.namespace }}
  labels:
    {{- include "cloudflared.labels" . | nindent 4 }}
type: Opaque
data:
  # Base64 encoded Cloudflare Tunnel token
  token: ""
{{- end }}
